### PR TITLE
Improved comments. Added error to callback calls. Fixed bug in song m…

### PR DESCRIPTION
**Pull request by joshvazquez**
…ove.

### CODE REVIEW

**Comment by joshvazquez** [comment]
@nstbayless @wchae @sinoforever one of you please review and merge

**Comment by nstbayless** [comment]
sure

**Comment by nstbayless** [comment]
Merged (0bead3b66fd401318ef992261d92bbb55ef30b41):

 - had to fix api.js and index.js to use new callback signatures
 - manager.createSong; the error is the second callback argument, not the first. Didn't change this, but this is weird.
 - playlist_manager.songIndex is a global field. Shouldn't it be specific to the playlist? (It doesn't much matter now since there is only one playlist)

**Comment by joshvazquez** [comment]
The song index is only relevant to the currently playing list to know the progress through the list and is not tracked across lists. So switching lists will start at the beginning or user-defined point, and not resume from the last time the list was played. Could be a possible enhancement for later if this is found to be useful.

**Comment by nstbayless** [comment]
Oh right, that makes sense. In that case there needs to be a way for the client to find out if the playlist it is viewing is the currently playing list. We can revisit that later.

**Pull request closed without merging**
