### PR TITLE
#16 First auto+manual pass of code style checking.

### PR DESCRIPTION
**Pull request by joshvazquez**

### CODE REVIEW

**Comment by joshvazquez** [comment]
@nstbayless @wchae @sinoforever one of you please review and merge

**Comment by nstbayless** [comment]
okay... this is going to be *very* tricky to merge because of the whitespace. Did you use js-beautify? If so, I can js-beautify before merging, which will clear up a lot of false positives.

**Comment by nstbayless** [comment]
okay :| I merged it. I'm pretty sure one or two semicolons got left behind. Not sure if you were using an automated styler but if so you're welcome to apply it again to fix those. I don't think that's necessary though.

**Comment by joshvazquez** [comment]
I used WebStorm "Reformat Code" and then went through it manually to correct anomalies. Too bad about all the false positives, not sure how else to deal with that.

**Comment by nstbayless** [comment]
It's OK, it only took about twenty minutes. Definitely not scalable though. I wonder if there are any githooks that could auto format code when committing.

**Pull request merged**
